redisMaster:
  image: redis
  replicas: 1
  service:
    port: 6379
    targetPort: 6379

redisReplica:
  image: redis
  replicas: 2
  service:
    port: 6379

frontend:
  image: gcr.io/google-samples/gb-frontend:v5
  replicas: 3
  service:
    type: NodePort
    port: 80
    targetPort: 80
