apiVersion: v1
kind: Service
metadata:
  name: redis-follower
  labels:
    app: redis
    tier: backend
    role: replica
spec:
  ports:
  - port: {{ .Values.redisReplica.service.port }}
    targetPort: 6379
  selector:
    app: redis
    tier: backend
    role: replica
