apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    tier: backend
    role: master
spec:
  ports:
  - port: {{ .Values.redisMaster.service.port }}
    targetPort: {{ .Values.redisMaster.service.targetPort }}
  selector:
    app: redis
    tier: backend
    role: master
