apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-follower
spec:
  selector:
    matchLabels:
      app: redis
      role: replica
      tier: backend
  replicas: {{ .Values.redisReplica.replicas }}
  template:
    metadata:
      labels:
        app: redis
        role: replica
        tier: backend
    spec:
      containers:
      - name: replica
        image: {{ .Values.redisReplica.image }}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 6379
